# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: prod

---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: login
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
      - name: login-container
        image: rajesh1803/login
        ports:
        - containerPort: 80
  
---          
apiVersion: v1
kind: Service
metadata:
  name: login-service
  namespace: prod
spec:
  type: NodePort
  selector:
    app: login
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
