# Top four items
apiVersion: v1
kind: Pod
metadata:
  name: multi-pod 
spec:
  containers:
  - name: nginx1
    image: nginx
    ports:
    - containerPort: 80
      
  - name: node-api
    image: nginx
    ports:
    - containerPort: 8080





